apiVersion: v1
kind: Service
metadeta:
  name: result-service
  lables:
    name: result-service
    app : demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    name: result-app-pod
    app: demo-voting-app