apiVersion: v1
kind: Pod
metadeta:
  name: voting-app-pod
  lables:
    name: voting-app-pod
    app: demo-voitng-app
spec:
  containers:
    - name: voting-app
      image: deep912/votingapp_vote
      ports:
        - containerPort: 80
